### ISSUE TITLE
Unable to connect with password

### ISSUE THREAD

**Issue by lorentzlasson** [agu-z/roc-pg#6]
I'm trying to run this example https://github.com/agu-z/roc-pg/blob/main/examples/query.roc, but using a password in clear text instead like so
```diff
@@ -21,7 +21,7 @@ task =
         host: "localhost",
         port: 5432,
         user: "postgres",
-        auth: None,
+        auth: Password "foo",
         database: "postgres",
     }
```

with this postgres setup in docker compose
```yml
services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foo
      POSTGRES_DB: postgres
```

but I get 

> [examples/query.roc:67] (TcpPerformErr UnsupportedAuth)
> Something went wrong

I can connect to it using `psql postgres://postgres:foo@localhost/postgres`

And if I switch the compose config to `POSTGRES_HOST_AUTH_METHOD: trust` I can connect from `query.roc`

> Connected!
> John: 32
> Julio: 23
